### PR TITLE
Monthly meeting 2019-05

### PR DESCRIPTION
**Pull request by jmbriano**
May monthly meeting Minutes

### CODE REVIEW

**Comment by jmbriano** [comment]
@amaliacardenas, @daverick, @jmbriano, @loriking, @raquelalvear, @saljuama: I'm adding the minutes  from yesterday meeting (MoM). Please review. as usual, the last to review should merge to master.

**Comment by raquelalvear** [comment]
LGTM!

**Comment by daverick** [comment]
lgtm

**Comment by amaliacardenas** [comment]
LGTM

**Comment by saljuama** [comment]
I am the last, so should be me doing the merge, but... i do not have write access to the repo :cry:

**Comment by jmbriano** [comment]
@saljuama don't worry, @loriking is missing and she has write access. Let's wait until Sunday. If not done by then I'll merge it

**Pull request merged**
