### PR TITLE
Discussion funding 

### PR DESCRIPTION
**Pull request by daverick**
I have started this PR to start the discussion about funding.
I propose that everybody add its point of view in terms of pros and cons to share it with the others.
Once we have this list we can value each point and see which decision is the best for us.

* [ ] list the pros and cons 
* [ ] make a dedicated session to see it together

### CODE REVIEW

**Comment by daverick** [comment]
Hi Tod@s,

May you have a look at this PR and add your Pros & Cons so that we can start the discussion about funding?

@amaliacardenas @saljuama @loriking @raquelalvear @jmbriano 

a+

**Comment by KimberleyCook** [comment]
Just a comment on this PR, you cannot set up a bank account or take money on behalf of codebar. It is illegal!

Any monetary funding you receive will have to go through the codebar bank account, you would then give me a receipt, I would then refund you.

**Comment by daverick** [comment]
@KimberleyCook it was not our intention. We are completely fine to manage the Barcelona Chapter without any legal entity here in Spain as long as we can (Brexit?). 
The objectives of this discussion is to see if we should call for some donations (to make more or better) or go on like today.

**Comment by KimberleyCook** [comment]
@daverick ok cool, just wanted to double check

**Comment by daverick** [comment]
## Status 201910 monthly meeting:

no advance.
Next steps has been defined:
* everyone list its pros and cons
* schedule a session to have a talk about it
btw: A yearly retro would be welcome too

**Review by saljuama — APPROVED** [review]

**Comment by saljuama** [comment]
We merged it to keep the content, but in regards of funding, the decision is that if someone wants to pursue a specific funding can create a one time initiative and close it whenever is accomplished

**Pull request merged**
