### PR TITLE
[Salva/Lori] proposal for new sessions

### PR DESCRIPTION
**Pull request by loriking**

### CODE REVIEW

**Comment by daverick** [comment]
* Could you move this files in `Processes/initiatives/__your_initiative__/` (that is what I used for pride month, could be something else)
* Could you use the normal markdown structure # ## and  ### to structure your document instead of italic. It will make it easier to understand you document and your intentions if it is well structured with tittles, substitles and so on.

I am a bit lost in your objectives, your proposed actions and type items to support your goal. I will wait untill you have structured your document in markdown style to comment on the content.

**Comment by loriking** [comment]
> * Could you move this files in `Processes/initiatives/__your_initiative__/` (that is what I used for pride month, could be something else)

I'm not clear what you want here. Can you elaborate.

> * Could you use the normal markdown structure # ## and  ### to structure your document instead of italic. It will make it easier to understand you document and your intentions if it is well structured with tittles, substitles and so on.

Updated.

> I am a bit lost in your objectives, your proposed actions and type items to support your goal. I will wait untill you have structured your document in markdown style to comment on the content.

Thanks for your feedback. This is the follow-up from the last organizers meeting on ways we can increase learning opportunities for students.

**Comment by daverick** [comment]
> > * Could you move this files in `Processes/initiatives/__your_initiative__/` (that is what I used for pride month, could be something else)
> 
> I'm not clear what you want here. Can you elaborate.

You file [pathway.md](pathway.md) is a the root of the repo. It would better in a specific folder `processes/initiatives/_your_initiative_/`

> > * Could you use the normal markdown structure # ## and  ### to structure your document instead of italic. It will make it easier to understand you document and your intentions if it is well structured with tittles, substitles and so on.
> 
> Updated.

I am afraid it is till noe clear. is the first paragraph about all the document or is at the same level as project, showcases or panel discussion? #,##, ### are not formatting option they are document architecting tools like section, chapter and subchapter   
 
> > I am a bit lost in your objectives, your proposed actions and type items to support your goal. I will wait untill you have structured your document in markdown style to comment on the content.
> 
> Thanks for your feedback. This is the follow-up from the last organizers meeting on ways we can increase learning opportunities for students.

this last phrase would be a nice intro in your document.

**Comment by daverick** [comment]
@loriking if you move this file to `processes/initiatives/_your_initiative_/` you will have my lgtm and merge

**Pull request closed without merging**
